name: PR flow

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  name_checker:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+\/([a-z])+' # Regex the title should match.
          allowed_prefixes: 'feature,fix,release,hotfix' # title should start with the given prefix
          disallowed_prefixes: 'feat/' # title should not start with the given prefix
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 150 # Max length of the title
