name: Release finish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y install git-flow

      - name: Event toJSON
        run: |
          echo "${{ toJSON(github.event) }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release/${{ github.event.inputs.version }}
          fetch-depth: 0

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Init git flow
        run: |
          git checkout master
          git checkout develop
          git flow init -d

      - name: Release finish
        run: |
          git flow release finish ${{ github.event.inputs.version }} -m "chore: version bumped" ${{ github.event.inputs.version }}

      - name: Release publish
        run: |
          git push --all --follow-tags --no-verify
