name: Release finish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.SUPER_AUTH_TOKEN }}

      - name: Event toJSON
        run: |
          echo "${{ toJSON(github.event) }}"

      - name: Install dependencies
        run: |
          sudo apt-get -y install git-flow

      - name: Init git flow
        run: |
          git flow init -d

      - name: Release finish
        run: |
          git flow release finish ${{ github.event.inputs.version }} -m "chore: version bumped" ${{ github.event.inputs.version }}

      - name: Release publish
        run: |
          git push --all --follow-tags --no-verify
