name: Release start
on:
  milestone:
    types:
      - closed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get -y install git-flow

      # - name: Event toJSON
      #   run: |
      #     echo "${{ toJSON(github.event) }}"

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          # fetch-depth: 0

      # - name: Init git flow
      #   run: |
      #     git flow init -d

      # - name: Release start
      #   run: |
      #     git flow release start ${{ github.event.milestone.title }}

      - name: Some changes
        run: |
          echo date > datetime.txt

      # - name: Release publish
      #   run: |
      #     git flow release publish

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: version bumped to ${{ github.event.milestone.title }}"
          committer: Release manager <noreply@github.com>
          author: Release manager <noreply@github.com>
          branch: release/${{ github.event.milestone.title }}
          base: master
          title: release/${{ github.event.milestone.title }}
          body: |
            Generated by closing milestone ${{ github.event.milestone.title }}
          labels: |
            Do not merge

      # - name: Create pull request
      #   uses: thomaseizinger/create-pull-request@1.0.0
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     head: release/${{ github.event.milestone.title }}
      #     base: master
      #     title: Release version ${{ github.event.milestone.title }}
      #     body: |
      #       Generated by closing milestone ${{ github.event.milestone.title }}

      # - name: Create pull request
      #   uses: gr2m/create-or-update-pull-request-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     title: release/${{ github.event.milestone.title }}
      #     body: Generated by closing milestone ${{ github.event.milestone.title }}
      #     commit-message: "ci: version bumped to ${{ github.event.milestone.title }}"
      #     branch: master
      #     labels: Do not merge
